name: Test GH actions for "stas" branch

on:
  push:
    branches: [ stas ]
  pull_request:
    branches: [ stas ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setting GoLang
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build
        run: make

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Test
        run: make test